import { OtpService } from '../../otp/services/otp.service';
import {
  BadRequestException,
  Global,
  Injectable,
  UnauthorizedException,
} from '@nestjs/common';
import { EventEmitter2 } from '@nestjs/event-emitter';
import * as bcrypt from 'bcrypt';
import {
  HttpResponseInterface,
  HttpStatusCodeEnum,
  SystemEventsEnum,
  User,
} from '@newmbani/types';
import { SettingsService } from '../../settings/services/settings.service';
import { ResetPasswordDTO } from '../dto/auth/reset-password.dto';
import { CustomHttpResponse } from '../../common';
import {
  UpdatePasswordDto,
  UpdatePasswordResetDto,
} from '../dto/users/update-password.dto';
import { UsersService } from './users.service';
import { UserModel } from '../schemas/user.schema';
import { ConfigService } from '@nestjs/config';
import { RedisService } from '../../redis/services/redis.service';
import { RedisPrefixEnum } from '../../redis/enums/redis-prefix.enum';
import { generateOTP } from '../utils/generate-otp-code';
import { generateResetCode } from '../utils/auto-generate-password-reset-code';

@Global()
@Injectable()
export class PasswordService {
  constructor(
    private readonly settingsService: SettingsService,
    private readonly otpService: OtpService,
    private readonly usersService: UsersService,
    private readonly config: ConfigService,
    private readonly redisService: RedisService,
    private eventEmitter: EventEmitter2,
  ) {
    //
  }

  /**
   * Request user password reset
   * @return {*} {Promise<any>}
   * @memberof AuthService
   */
  async requestPasswordReset(
    payload: ResetPasswordDTO,
  ): Promise<HttpResponseInterface> {
    const { email } = payload;
    const user: User | null = (await this.usersService.findOne({ email })).data;
    if (user) {
      const userId = user._id.toString();
      let token = null;
      let otp = null;
      if (user.twoFactorEnabled) {
        otp = generateOTP();
        await this.otpService.setOTPCode({ userId, otp });
      } else {
        token = generateResetCode();
        await this.setPasswordResetToken({ userId, token });
      }

      // Emit the event that the employee password request has been initiated
      this.eventEmitter.emit(SystemEventsEnum.PasswordResetRequested, {
        user,
        token,
        otp,
      });

      return new CustomHttpResponse({
        statusCode: HttpStatusCodeEnum.OK,
        message: `A password reset email has been sent!`,
        data: null,
      });
    }
    return new CustomHttpResponse({
      statusCode: HttpStatusCodeEnum.UNAUTHORIZED,
      message: 'User with that email is not registered',
      data: null,
    });
  }

  async verifyPasswordReset(data: {
    email: string;
    otp?: string;
    token?: string;
  }): Promise<HttpResponseInterface> {
    try {
      return new CustomHttpResponse({
        statusCode: HttpStatusCodeEnum.BAD_REQUEST,
        message: 'Failed to reset password. ',
        data: null,
      });
    } catch (error) {
      return new CustomHttpResponse({
        statusCode: HttpStatusCodeEnum.BAD_REQUEST,
        message: 'Failed to reset password. ' + error.message,
        data: error,
      });
    }
  }

  /**
   * Update user password using the otp code generated by the app
   *
   * @param {UpdatePasswordWithOTPDto} payload
   * @return {*}  {Promise<HttpResponseInterface>}
   * @memberof UsersService
   */
  async processPasswordReset(
    data: UpdatePasswordResetDto,
  ): Promise<HttpResponseInterface> {
    try {
      const { otpCode, resetToken, userId, newPassword } = data;
      if (!otpCode && !resetToken) {
        throw new Error('Either otpCode or resetToken must be provided');
      }

      if (otpCode) {
        // reset using otp
        return await this.resetPasswordViaOTP({ userId, otpCode, newPassword });
      } else {
        // reset using token
        return await this.resetPasswordViaToken({
          userId,
          resetToken,
          newPassword,
        });
      }
    } catch (error) {
      return new CustomHttpResponse({
        statusCode: HttpStatusCodeEnum.BAD_REQUEST,
        message: 'There was an issue resetting your password. Try again',
        data: error,
      });
    }
  }

  async resetPasswordViaOTP(data: {
    userId: string;
    otpCode: string;
    newPassword: string;
  }): Promise<HttpResponseInterface> {
    try {
      const { otpCode, userId } = data;
      // get the user using the password reset token
      const otp = await this.otpService.getOTPCode(userId);
      if (!otp || otp !== otpCode) {
        throw new Error('The OTP code provided does not exist or is expired');
      }
      const user: User | undefined = await UserModel.findOne({
        _id: userId,
      }).exec();

      if (!user) {
        throw new Error('User not found');
      }

      // Invalidate the OTP after successful verification
      await this.otpService.invalidateOTPCode(userId);

      //
      return await this.updatePassword({
        userId: user._id.toString(),
        newPassword: data.newPassword,
      });
    } catch (error) {
      return new CustomHttpResponse({
        statusCode: HttpStatusCodeEnum.BAD_REQUEST,
        message: 'Failed to reset password. ' + error.message,
        data: error,
      });
    }
  }

  async resetPasswordViaToken(data: {
    userId: string;
    resetToken: string;
    newPassword: string;
  }): Promise<HttpResponseInterface> {
    try {
      const { resetToken, newPassword, userId } = data;
      // get the user using the password reset token
      const storedUserId = await this.getPasswordResetToken(resetToken);
      if (!storedUserId || storedUserId !== userId) {
        throw new Error('The token provided does not exist or is expired');
      }
      const user: User | undefined = await UserModel.findOne({
        _id: userId,
      }).exec();

      if (!user) {
        throw new Error('User not found');
      }

      // Invalidate the OTP after successful verification
      await this.setPasswordResetToken({ userId, token: null });

      //
      return await this.updatePassword({
        userId: user._id.toString(),
        newPassword,
      });
    } catch (error) {
      return new CustomHttpResponse({
        statusCode: HttpStatusCodeEnum.BAD_REQUEST,
        message: 'Failed to reset password. ' + error.message,
        data: error,
      });
    }
  }

  async processUpdatePasswordWhenLoggedIn(data: {
    updatePasswordDto: UpdatePasswordDto;
    userId: string;
  }): Promise<HttpResponseInterface> {
    try {
      const { updatePasswordDto, userId } = data;
      const { currentPassword, newPassword } = updatePasswordDto;
      // get the user using the userId
      const user: User | undefined = await UserModel.findOne({
        _id: userId,
      }).exec();

      if (!user) {
        throw new Error('User not found');
      }
      const passwordMatch = await bcrypt.compare(
        currentPassword,
        user.password,
      );
      if (!passwordMatch) {
        throw new Error('Current password is incorrect');
      }

      return this.updatePassword({ userId, newPassword });
    } catch (error) {
      return new CustomHttpResponse({
        statusCode: HttpStatusCodeEnum.BAD_REQUEST,
        message: 'There was an issue resetting your password. Try again',
        data: error,
      });
    }
  }

  /**
   * Update Password functionality
   *
   * @param {UpdatePasswordDto} updatePasswordDto
   * @return {*}  {Promise<HttpResponseInterface>}
   * @memberof UsersService
   */
  async updatePassword(data: {
    userId: string;
    newPassword: string;
  }): Promise<HttpResponseInterface> {
    try {
      const { newPassword, userId } = data;

      let user = await UserModel.findById<User>(userId).exec();
      if (!user) {
        return new CustomHttpResponse({
          statusCode: HttpStatusCodeEnum.BAD_REQUEST,
          message: 'User not Found',
          data: user,
        });
      }
      const filter = { _id: userId };
      // Hash the password
      const salt = await bcrypt.genSalt();
      const hashedPassword = await bcrypt.hash(newPassword, salt);

      // Update the password
      user = await UserModel.findOneAndUpdate(
        filter,
        {
          password: hashedPassword,
          isPasswordDefault: false,
          updatedAt: new Date(),
          lastPasswordChange: new Date(),
        },
        {
          returnOriginal: false,
        },
      );

      // Emit the event that the password has been updated
      this.eventEmitter.emit(SystemEventsEnum.PASSWORD_RESET_SUCCESS, user);

      return new CustomHttpResponse({
        statusCode: HttpStatusCodeEnum.OK,
        message: 'Your password was updated successfully',
        data: user,
      });
    } catch (error) {
      return new CustomHttpResponse({
        statusCode: HttpStatusCodeEnum.OK,
        message: error.message,
        data: error,
      });
    }
  }

  async verifyResetToken(data: { token: string }) {
    try {
      const { token } = data;
      let userId = await this.getPasswordResetToken(token);
      if (!userId)
        throw new UnauthorizedException('Invalid or expired reset token');

      const user = await UserModel.findOne<User>({ _id: userId }).exec();
      if (!user) throw new BadRequestException('User not found');
      userId = user._id.toString();
      if (user.twoFactorEnabled) {
        const otp = generateOTP();
        await this.otpService.setOTPCode({ otp, userId });

        // Emit the event that the employee password request has been initiated
        this.eventEmitter.emit(SystemEventsEnum.PasswordResetRequested, {
          user,
          token,
          otp,
        });
        return new CustomHttpResponse({
          message: 'OTP has been sent to your email.',
          statusCode: HttpStatusCodeEnum.OK,
          data: {
            userId,
            requiresOtp: true,
          },
        });
      }
      return new CustomHttpResponse({
        message: 'Reset token is valid.',
        statusCode: HttpStatusCodeEnum.OK,
        data: {
          userId,
          requiresOtp: false,
        },
      });
    } catch (error) {
      console.error(error);
      return new CustomHttpResponse({
        message: 'Unable to complete your request. ' + error.message,
        statusCode: HttpStatusCodeEnum.INTERNAL_SERVER_ERROR,
        data: {
          requiresOtp: false,
        },
      });
    }
  }

  /**
   * Set password reset token to the user data
   *
   * @param {{ token: string; userId: string }} payload
   * @return {*}
   * @memberof UsersService
   */
  async setPasswordResetToken(payload: {
    userId: string;
    token: string;
  }): Promise<any> {
    const { userId, token } = payload;
    // Set token expiry time
    const expiriesIn =
      (this.config.get<number>('PASSWORD_RESET_TOKEN_EXPIRY') || 10) * 60; // minutes
    const prefix = RedisPrefixEnum.PASSWORD_RESET_TOKEN;
    // Set the token to redis cache {prefix}:{token} = userId
    await this.redisService.setKeyWithExpiry({
      prefix,
      key: token,
      value: userId,
      expiriesIn,
    });
  }

  async getPasswordResetToken(token: string): Promise<any> {
    const prefix = RedisPrefixEnum.PASSWORD_RESET_TOKEN;
    // Get the token from redis cache
    return await this.redisService.get({ prefix, key: token });
  }

  async invalidatePasswordResetToken(token: string): Promise<any> {
    const prefix = RedisPrefixEnum.PASSWORD_RESET_TOKEN;
    // Delete the token from redis cache
    return await this.redisService.delete({ prefix, key: token });
  }
}
